///测试demo数据,图片失效可自行替换,数据量可自行增加,结构不可更改

const Data = [
  {
    'id': 1,
    'name': '牛油鲜果沙拉',
    'pirce': 45.0,
    'url': 'images/1.jpg',
    'mealType': '当日午餐',
    'isCollect': false,
  },
  {
    'id': 2,
    'name': '日本和牛牛排',
    'pirce': 235.0,
    'url': 'images/2.jpg',
    'mealType': '次日午餐',
    'isCollect': false,
  },
  {
    'id': 3,
    'name': '水蜜桃甜品',
    'pirce': 60.0,
    'url': 'images/3.jpg',
    'mealType': '当日午餐',
    'isCollect': true,
  },
  {
    'id': 4,
    'name': '牛油鲜果沙拉',
    'pirce': 45.0,
    'url': 'images/1.jpg',
    'mealType': '当日午餐',
    'isCollect': false,
  },
  {
    'id': 5,
    'name': '日本和牛牛排',
    'pirce': 235.0,
    'url': 'images/2.jpg',
    'mealType': '次日午餐',
    'isCollect': false,
  },
  {
    'id': 6,
    'name': '水蜜桃甜品',
    'pirce': 60.0,
    'url': 'images/3.jpg',
    'mealType': '当日午餐',
    'isCollect': true,
  },
  {
    'id': 7,
    'name': '牛油鲜果沙拉',
    'pirce': 45.0,
    'url': 'images/1.jpg',
    'mealType': '当日午餐',
    'isCollect': false,
  },
  {
    'id': 8,
    'name': '日本和牛牛排',
    'pirce': 235.0,
    'url': 'images/2.jpg',
    'mealType': '次日午餐',
    'isCollect': false,
  },
  {
    'id': 9,
    'name': '水蜜桃甜品',
    'pirce': 60.0,
    'url': 'images/3.jpg',
    'mealType': '当日午餐',
    'isCollect': true,
  },
  {
    'id': 10,
    'name': '牛油鲜果沙拉',
    'pirce': 45.0,
    'url': 'images/1.jpg',
    'mealType': '当日午餐',
    'isCollect': false,
  },
  {
    'id': 11,
    'name': '日本和牛牛排',
    'pirce': 235.0,
    'url': 'images/2.jpg',
    'mealType': '次日午餐',
    'isCollect': false,
  },
  {
    'id': 12,
    'name': '水蜜桃甜品',
    'pirce': 60.0,
    'url': 'images/3.jpg',
    'mealType': '当日午餐',
    'isCollect': true,
  },
  {
    'id': 13,
    'name': '牛油鲜果沙拉',
    'pirce': 45.0,
    'url': 'images/1.jpg',
    'mealType': '当日午餐',
    'isCollect': false,
  },
  {
    'id': 14,
    'name': '日本和牛牛排',
    'pirce': 235.0,
    'url': 'images/2.jpg',
    'mealType': '次日午餐',
    'isCollect': false,
  },
  {
    'id': 15,
    'name': '水蜜桃甜品',
    'pirce': 60.0,
    'url': 'images/3.jpg',
    'mealType': '当日午餐',
    'isCollect': true,
  },
  {
    'id': 16,
    'name': '牛油鲜果沙拉',
    'pirce': 45.0,
    'url': 'images/1.jpg',
    'mealType': '当日午餐',
    'isCollect': false,
  },
  {
    'id': 17,
    'name': '日本和牛牛排',
    'pirce': 235.0,
    'url': 'images/2.jpg',
    'mealType': '次日午餐',
    'isCollect': false,
  },
  {
    'id': 18,
    'name': '水蜜桃甜品',
    'pirce': 60.0,
    'url': 'images/3.jpg',
    'mealType': '当日午餐',
    'isCollect': true,
  },
  {
    'id': 19,
    'name': '牛油鲜果沙拉',
    'pirce': 45.0,
    'url': 'images/1.jpg',
    'mealType': '当日午餐',
    'isCollect': false,
  },
  {
    'id': 20,
    'name': '日本和牛牛排',
    'pirce': 235.0,
    'url': 'images/2.jpg',
    'mealType': '次日午餐',
    'isCollect': false,
  }
];
